'use client';
import { authFetch } from '../auth-fetch';
import { FormEvent, useEffect, useState } from 'react';
import { Panel, Table, StatusChip } from '../ui';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';
type Category={id:string;name:string;slug:string};
type Customer={id:string;name:string;phone?:string|null;email?:string|null;customerType:string};
type Branch={id:string;code:string;name:string;isActive:boolean};
type Warehouse={id:string;branchId:string;code:string;name:string;isActive:boolean;branch?:Branch};
type WarehouseLocation={id:string;warehouseId:string;parentId?:string|null;code:string;name:string;type:string;barcode?:string|null;capacity?:string|number|null;isActive:boolean};
type Ref={id:string;type:string;code:string;name:string;isActive:boolean};
type Product={id:string;sku:string;name:string;unit:string};
type Page<T>={items:T[]};
async function call<T>(token:string,path:string,init?:RequestInit){const r=await authFetch(`${API}${path}`,token,{...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init?.headers??{})}});const d=await r.json();if(!r.ok)throw new Error(Array.isArray(d.message)?d.message.join(', '):d.message??'Request gagal');return d as T;}

export default function MasterDataView({token}:{token:string}){
 const [categories,setCategories]=useState<Category[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[branches,setBranches]=useState<Branch[]>([]),[warehouses,setWarehouses]=useState<Warehouse[]>([]),[locations,setLocations]=useState<WarehouseLocation[]>([]),[refs,setRefs]=useState<Ref[]>([]),[products,setProducts]=useState<Product[]>([]);
 const [msg,setMsg]=useState('');
 const [cat,setCat]=useState(''),[cust,setCust]=useState({name:'',phone:'',email:'',customerType:'RETAIL'}),[wh,setWh]=useState({branchId:'',code:'',name:''}),[location,setLocation]=useState({warehouseId:'',parentId:'',code:'',name:'',type:'BIN',barcode:'',capacity:''}),[ref,setRef]=useState({type:'BRAND',code:'',name:''}),[barcode,setBarcode]=useState({productId:'',code:'',unitCode:'',quantityFactor:1}),[price,setPrice]=useState({productId:'',branchId:'',segmentCode:'RETAIL',unitCode:'',minQty:1,price:0});
 async function refresh(){const [c,cu,b,w,l,r,p]=await Promise.all([call<Category[]>(token,'/master-data/categories'),call<Customer[]>(token,'/master-data/customers'),call<Branch[]>(token,'/master-data/branches'),call<Warehouse[]>(token,'/master-data/warehouses'),call<WarehouseLocation[]>(token,'/master-data/warehouse-locations'),call<Ref[]>(token,'/master-data/references'),call<Page<Product>>(token,'/products?limit=100')]);setCategories(c);setCustomers(cu);setBranches(b);setWarehouses(w);setLocations(l);setRefs(r);setProducts(p.items);setWh(v=>({...v,branchId:v.branchId||b[0]?.id||''}));setLocation(v=>({...v,warehouseId:v.warehouseId||w[0]?.id||''}));setBarcode(v=>{const product=p.items.find(x=>x.id===(v.productId||p.items[0]?.id));return {...v,productId:v.productId||p.items[0]?.id||'',unitCode:v.unitCode||product?.unit||''};});setPrice(v=>{const product=p.items.find(x=>x.id===(v.productId||p.items[0]?.id));return {...v,productId:v.productId||p.items[0]?.id||'',branchId:v.branchId||b[0]?.id||'',unitCode:v.unitCode||product?.unit||''};});}
 useEffect(()=>{void refresh().catch(e=>setMsg(e instanceof Error?e.message:'Gagal memuat master data'));},[token]);
 const unitRefs=refs.filter(x=>x.type==='UNIT'&&x.isActive);
 const selectedBarcodeProduct=products.find(x=>x.id===barcode.productId);
 const selectedPriceProduct=products.find(x=>x.id===price.productId);
 async function submit(e:FormEvent,path:string,body:unknown,after:()=>void){e.preventDefault();setMsg('');try{await call(token,path,{method:'POST',body:JSON.stringify(body)});after();await refresh();setMsg('Data tersimpan.');}catch(err){setMsg(err instanceof Error?err.message:'Gagal menyimpan');}}
 return <>
  <section className="grid2">
   <Panel eyebrow="KATALOG" title="Kategori"><form className="formStack" onSubmit={e=>void submit(e,'/master-data/categories',{name:cat},()=>setCat(''))}><label>Nama kategori<input required value={cat} onChange={e=>setCat(e.target.value)}/></label><button>Simpan kategori</button></form><Table head={['Nama','Slug']} rows={categories.map(x=>[<strong>{x.name}</strong>,x.slug])} empty="Belum ada kategori"/></Panel>
   <Panel eyebrow="PELANGGAN" title="Customer Master"><form className="formStack" onSubmit={e=>void submit(e,'/master-data/customers',cust,()=>setCust({name:'',phone:'',email:'',customerType:'RETAIL'}))}><label>Nama<input required value={cust.name} onChange={e=>setCust({...cust,name:e.target.value})}/></label><label>Telepon<input value={cust.phone} onChange={e=>setCust({...cust,phone:e.target.value})}/></label><label>Email<input type="email" value={cust.email} onChange={e=>setCust({...cust,email:e.target.value})}/></label><label>Segmen<input value={cust.customerType} onChange={e=>setCust({...cust,customerType:e.target.value})}/></label><button>Simpan pelanggan</button></form><Table head={['Nama','Kontak','Segmen']} rows={customers.slice(0,20).map(x=>[<strong>{x.name}</strong>,x.phone||x.email||'-',x.customerType])} empty="Belum ada pelanggan"/></Panel>
  </section>
  <section className="grid2">
   <Panel eyebrow="ORGANISASI" title="Cabang & Gudang"><form className="formStack" onSubmit={e=>void submit(e,'/master-data/warehouses',wh,()=>setWh({...wh,code:'',name:''}))}><label>Cabang<select required value={wh.branchId} onChange={e=>setWh({...wh,branchId:e.target.value})}>{branches.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Kode gudang<input required value={wh.code} onChange={e=>setWh({...wh,code:e.target.value})}/></label><label>Nama gudang<input required value={wh.name} onChange={e=>setWh({...wh,name:e.target.value})}/></label><button>Simpan gudang</button></form><Table head={['Kode','Nama','Status']} rows={warehouses.map(x=>[<strong>{x.code}</strong>,x.name,<StatusChip status={x.isActive?'ACTIVE':'INACTIVE'}/>])} empty="Belum ada gudang"/></Panel>
   <Panel eyebrow="LOKASI GUDANG" title="Zone / Rack / Bin"><form className="formStack" onSubmit={e=>void submit(e,'/master-data/warehouse-locations',{warehouseId:location.warehouseId,parentId:location.parentId||undefined,code:location.code,name:location.name,type:location.type,barcode:location.barcode||undefined,capacity:location.capacity===''?undefined:Number(location.capacity)},()=>setLocation({...location,parentId:'',code:'',name:'',barcode:'',capacity:''}))}><label>Gudang<select required value={location.warehouseId} onChange={e=>setLocation({...location,warehouseId:e.target.value,parentId:''})}>{warehouses.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Parent lokasi<select value={location.parentId} onChange={e=>setLocation({...location,parentId:e.target.value})}><option value="">Tidak ada / root</option>{locations.filter(x=>x.warehouseId===location.warehouseId&&x.isActive).map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Tipe<select value={location.type} onChange={e=>setLocation({...location,type:e.target.value})}>{['ZONE','AISLE','RACK','BIN'].map(x=><option key={x}>{x}</option>)}</select></label><label>Kode<input required value={location.code} onChange={e=>setLocation({...location,code:e.target.value})}/></label><label>Nama<input required value={location.name} onChange={e=>setLocation({...location,name:e.target.value})}/></label><label>Barcode lokasi<input value={location.barcode} onChange={e=>setLocation({...location,barcode:e.target.value})}/></label><label>Kapasitas<input type="number" min="0" value={location.capacity} onChange={e=>setLocation({...location,capacity:e.target.value})}/></label><button>Simpan lokasi</button></form><Table head={['Gudang','Kode','Nama','Tipe']} rows={locations.slice(0,40).map(x=>[warehouses.find(w=>w.id===x.warehouseId)?.code??'-',<strong>{x.code}</strong>,x.name,x.type])} empty="Belum ada lokasi gudang"/></Panel>
   <Panel eyebrow="REFERENCE MASTER" title="Brand, Unit, Bank, Courier, Payment"><form className="formStack" onSubmit={e=>void submit(e,'/master-data/references',ref,()=>setRef({...ref,code:'',name:''}))}><label>Tipe<select value={ref.type} onChange={e=>setRef({...ref,type:e.target.value})}>{['BRAND','UNIT','BANK','COURIER','PAYMENT_METHOD'].map(x=><option key={x}>{x}</option>)}</select></label><label>Kode<input required value={ref.code} onChange={e=>setRef({...ref,code:e.target.value})}/></label><label>Nama<input required value={ref.name} onChange={e=>setRef({...ref,name:e.target.value})}/></label><button>Simpan referensi</button></form><Table head={['Tipe','Kode','Nama']} rows={refs.slice(0,30).map(x=>[x.type,<strong>{x.code}</strong>,x.name])} empty="Belum ada reference master"/></Panel>
  </section>
  <section className="grid2">
   <Panel eyebrow="BARCODE" title="Barcode & Konversi Unit"><form className="formStack" onSubmit={e=>void submit(e,`/master-data/products/${barcode.productId}/barcodes`,{code:barcode.code,isPrimary:false,unitCode:barcode.unitCode||selectedBarcodeProduct?.unit,quantityFactor:Number(barcode.quantityFactor)},()=>setBarcode({...barcode,code:'',quantityFactor:1}))}><label>Produk<select required value={barcode.productId} onChange={e=>{const product=products.find(x=>x.id===e.target.value);setBarcode({...barcode,productId:e.target.value,unitCode:product?.unit??''});}}>{products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name} · base {x.unit}</option>)}</select></label><label>Barcode alternatif<input required value={barcode.code} onChange={e=>setBarcode({...barcode,code:e.target.value})}/></label><label>Unit jual<select value={barcode.unitCode||selectedBarcodeProduct?.unit||''} onChange={e=>setBarcode({...barcode,unitCode:e.target.value})}>{selectedBarcodeProduct&&<option value={selectedBarcodeProduct.unit}>{selectedBarcodeProduct.unit} (base)</option>}{unitRefs.filter(x=>x.code!==selectedBarcodeProduct?.unit).map(x=><option key={x.id} value={x.code}>{x.code} · {x.name}</option>)}</select></label><label>Isi per unit<input type="number" min="1" step="1" value={barcode.quantityFactor} onChange={e=>setBarcode({...barcode,quantityFactor:Math.max(1,Math.floor(Number(e.target.value)||1))})}/></label><button>Tambah barcode / konversi</button></form><p className="sectionHelp">Contoh: base PCS, barcode BOX dengan isi 12. Inventory tetap 12 PCS; POS menyimpan jejak BOX dan server menghitung harga BOX secara authoritative.</p></Panel>
   <Panel eyebrow="PRICING" title="Harga Cabang / Segmen / Unit / Kuantitas"><form className="formStack" onSubmit={e=>void submit(e,`/master-data/products/${price.productId}/prices`,{branchId:price.branchId||undefined,segmentCode:price.segmentCode,unitCode:price.unitCode||selectedPriceProduct?.unit,minQty:Number(price.minQty),price:Number(price.price)},()=>setPrice({...price,minQty:1,price:0}))}><label>Produk<select required value={price.productId} onChange={e=>{const product=products.find(x=>x.id===e.target.value);setPrice({...price,productId:e.target.value,unitCode:product?.unit??''});}}>{products.map(x=><option key={x.id} value={x.id}>{x.sku} · {x.name}</option>)}</select></label><label>Cabang<select value={price.branchId} onChange={e=>setPrice({...price,branchId:e.target.value})}><option value="">Semua cabang</option>{branches.map(x=><option key={x.id} value={x.id}>{x.code} · {x.name}</option>)}</select></label><label>Segmen<input value={price.segmentCode} onChange={e=>setPrice({...price,segmentCode:e.target.value})}/></label><label>Unit harga<select value={price.unitCode||selectedPriceProduct?.unit||''} onChange={e=>setPrice({...price,unitCode:e.target.value})}>{selectedPriceProduct&&<option value={selectedPriceProduct.unit}>{selectedPriceProduct.unit} (base)</option>}{unitRefs.filter(x=>x.code!==selectedPriceProduct?.unit).map(x=><option key={x.id} value={x.code}>{x.code} · {x.name}</option>)}</select></label><label>Minimal qty unit jual<input type="number" min="1" step="1" value={price.minQty} onChange={e=>setPrice({...price,minQty:Math.max(1,Math.floor(Number(e.target.value)||1))})}/></label><label>Harga per unit jual<input required type="number" min="0" value={price.price} onChange={e=>setPrice({...price,price:Number(e.target.value)})}/></label><button>Simpan harga</button></form><p className="sectionHelp">Harga unit kemasan hanya boleh dibuat bila konversi barcode untuk unit tersebut sudah ada. Server memvalidasi factor, stok base unit, segmen, cabang, dan minimum quantity.</p></Panel>
  </section>
  {msg&&<div className="notice">{msg}</div>}
 </>;
}
